# Generated by Django 5.2.1 on 2025-06-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
