# Generated by Django 5.2.1 on 2025-06-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_author_photo_url_album_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='item',
        ),
        migrations.RemoveField(
            model_name='category',
            name='item',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='item',
        ),
    ]
